# Generated by Django 2.1.1 on 2018-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180929_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
