# Generated by Django 2.1.1 on 2018-10-05 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20180929_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Shopping_cart',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shoppingCart',
        ),
    ]
