# Generated by Django 2.1.1 on 2018-10-05 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False   
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_transaction_shopping_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_cart',
            new_name='Shoppingcart',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='shopping_cart',
            new_name='shoppingcart',
        ),
    ]
